FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
git \
build-essential \
&& rm -rf /var/lib/apt/lists/*

COPY requirements-dbt.txt .

RUN pip install --no-cache-dir -r requirements-dbt.txt

COPY . .

ENV DBT_PROFILES_DIR=/app

CMD ["bash", "-c", "dbt deps && dbt snapshot && dbt build --select +fact_sales"]