services:
 scheduler:
   volumes:
     - "C:/Users/avi72/AppData/Roaming/gcloud:/usr/local/airflow/gcloud:ro"

 api-server:
   volumes:
     - "C:/Users/avi72/AppData/Roaming/gcloud:/usr/local/airflow/gcloud:ro"

 triggerer:
   volumes:
     - "C:/Users/avi72/AppData/Roaming/gcloud:/usr/local/airflow/gcloud:ro"

 dag-processor:
   volumes:
     - "C:/Users/avi72/AppData/Roaming/gcloud:/usr/local/airflow/gcloud:ro"