version: 2

sources:
  - name: retailer_raw
    database: retailer-data-engineer
    schema: raw_local

    tables:
      - name: flatfile_orders
      - name: flatfile_customers
      - name: flatfile_order_items
      - name: flatfile_products
      - name: flatfile_returns
      - name: flatfile_stores
      - name: flatfile_supplier_shipments
      - name: flatfile_inventory_snapshot
      - name: flatfile_promotions
      