audit_table : retailer-data-engineer.raw_local.audit_files
sources:
  orders:
    enabled: true
    file_type: csv
    file_pattern: orders_*.csv
    source_path: gs://retailer_landing_data/orders/
    raw_path: gs://retailer_data/raw/orders
    archive_path: gs://retailer_data/archive/orders
    #rejected_path: data/rejected
    target_table: retailer-data-engineer.raw_local.flatfile_orders
    audit_table : retailer-data-engineer.raw_local.audit_files
    load_type: incremental
    partition_column: sale_date
    delimiter: ","
    header: true
    duplicate_check: true

  # order_items:
  #   enabled: true
  #   file_type: csv
  #   source_path: gs://retailer_landing_data/order_items
  #   raw_path: gs://retailer_data/raw/orders_item
  #   archive_path: gs://retailer_data/archive/orders_item
  #   #rejected_path: data/rejected
  #   file_pattern: order_items_*.csv
  #   target_table: raw_order_items
  #   primary_key: order_item_id
  #   load_type: incremental

  # customers:
  #   enabled: true
  #   file_type: json
  #   source_path: gs://retailer_landing_data/customers
  #   raw_path: gs://retailer_data/raw/customers
  #   archive_path: gs://retailer_data/archive/customers
  #   #rejected_path:
  #   file_pattern: customers_snapshot_*.json
  #   target_table: raw_customers
  #   primary_key: customer_id
  #   load_type: scd2

  # products:
  #   enabled: false
  #   file_type: excel
  #   source_path: gs://retailer_data/raw/products
  #   raw_path:
  #   archive_path:
  #   rejected_path:
  #   file_pattern: product_master_snapshot_*.xlsx
  #   target_table: raw_products
  #   primary_key: product_id
  #   load_type: scd2

  # stores:
  #   enabled: false
  #   file_type: csv
  #   source_path: data/raw/stores
  #   raw_path:
  #   archive_path:
  #   rejected_path:
  #   file_pattern: store_master_snapshot_*.csv
  #   target_table: raw_stores
  #   primary_key: store_id
  #   load_type: full

  # inventory_snapshot:
  #   enabled: false
  #   file_type: parquet
  #   source_path: data/raw/inventory
  #   raw_path:
  #   archive_path:
  #   rejected_path:
  #   file_pattern: inventory_snapshot_*.parquet
  #   target_table: raw_inventory_snapshot
  #   primary_key: snapshot_date,store_id,product_id
  #   load_type: incremental
  #   partition_column: snapshot_date

  # promotions:
  #   enabled: false
  #   file_type: csv
  #   source_path: data/raw/promotions
  #   raw_path:
  #   archive_path:
  #   rejected_path:
  #   file_pattern: promotions_*.csv
  #   target_table: raw_promotions
  #   primary_key: promotion_id
  #   load_type: full

  # returns:
  #   enabled: false
  #   file_type: csv
  #   source_path: data/raw/returns
  #   raw_path:
  #   archive_path:
  #   rejected_path:
  #   file_pattern: returns_*.csv
  #   target_table: raw_returns
  #   primary_key: return_id
  #   load_type: incremental
  #   partition_column: return_date

  # supplier_shipments:
  #   enabled: false
  #   file_type: csv
  #   source_path: data/raw/supplier_shipments
  #   raw_path:
  #   archive_path:
  #   rejected_path:
  #   file_pattern: supplier_shipments_*.csv
  #   target_table: raw_supplier_shipments
  #   primary_key: shipment_id
  #   load_type: incremental
  #   partition_column: shipment_date

  # web_events:
  #   enabled: false
  #   file_type: json
  #   source_path: data/raw/web_events
  #   raw_path:
  #   archive_path:
  #   rejected_path:
  #   file_pattern: web_events_*.json
  #   target_table: raw_web_events
  #   primary_key: event_id
  #   load_type: append
  #   partition_column: event_timestamp
